## Load information 
### Gather solar radiation data from multiple files

In [1]:
import pandas as pd
import glob
import os

from shapely.geometry import Point
from helper import *

path = 'data/radiation/'
files = glob.glob(os.path.join(path, '*.csv'))

radiation_data = []
for f in files:
    # Read CSV skipping first two lines and using the third line as header
    df = pd.read_csv(f, skiprows=2)
    # Extract lat/lon from filename (e.g., xxxxxxx_41.88_-87.63_yyyy.csv)
    lat, lon = map(float, os.path.basename(f).split('_')[1:3])
    df['lat'] = lat
    df['lon'] = lon
    df['geometry'] = Point(lon, lat)
    radiation_data.append(df)

radiation_df = pd.concat(radiation_data, ignore_index=True)

Convert stadard dataframe into geopandas dataframe. This will still have multiple timestamps (year, month, day, hour) per (DHI, DNI, GHI) triplet.

In [2]:
import geopandas as gpd

radiation_gdf = gpd.GeoDataFrame(radiation_df, geometry='geometry', crs='EPSG:4326')
radiation_gdf

,Year,Month,Day,Hour,Minute,DHI,GHI,DNI,Solar Zenith Angle,lat,lon,geometry
0,2023,1,1,0,0,0,0,0,106.22,41.98,-87.73,POINT (-87.73 41.98)
1,2023,1,1,1,0,0,0,0,117.11,41.98,-87.73,POINT (-87.73 41.98)
2,2023,1,1,2,0,0,0,0,128.23,41.98,-87.73,POINT (-87.73 41.98)
3,2023,1,1,3,0,0,0,0,139.25,41.98,-87.73,POINT (-87.73 41.98)
4,2023,1,1,4,0,0,0,0,149.61,41.98,-87.73,POINT (-87.73 41.98)
...,...,...,...,...,...,...,...,...,...,...,...,...
6806515,2023,12,31,19,0,106,106,0,66.51,41.68,-87.71,POINT (-87.71 41.68)
6806516,2023,12,31,20,0,42,42,0,70.99,41.68,-87.71,POINT (-87.71 41.68)
6806517,2023,12,31,21,0,50,50,0,77.68,41.68,-87.71,POINT (-87.71 41.68)
6806518,2023,12,31,22,0,10,10,0,85.96,41.68,-87.71,POINT (-87.71 41.68)
6806519,2023,12,31,23,0,0,0,0,95.76,41.68,-87.71,POINT (-87.71 41.68)

In [3]:
print(radiation_gdf.crs)

EPSG:4326

To have a single geopandas data frame with a single triplet per coordinate which will be the year average.

In [4]:
# not removing zeros because those were measurements, not nan
sum_gdf = radiation_gdf.groupby(['lat', 'lon']).agg({
    "GHI": ["mean", "sum"],
    "DNI": ["mean", "sum"],
    "DHI": ["mean", "sum"]
}) 

# Flatten the MultiIndex columns
sum_gdf.columns = ['_'.join(col).strip() for col in sum_gdf.columns.values]

# Reset index to make it easier to join back later
sum_gdf = sum_gdf.reset_index()

sum_gdf['geometry'] = sum_gdf.apply(lambda row: Point(row['lon'], row['lat']), axis=1)
sum_gdf['GHI/DNI'] = sum_gdf['GHI_mean']/sum_gdf['DNI_mean']
sum_gdf = gpd.GeoDataFrame(sum_gdf, geometry='geometry', crs='EPSG:4326') 
sum_gdf = sum_gdf.to_crs('EPSG:3435')  # Chicago's local CRS
sum_gdf

,lat,lon,GHI_mean,GHI_sum,DNI_mean,DNI_sum,DHI_mean,DHI_sum,geometry,GHI/DNI
0,41.64,-87.97,165.969064,1453889,182.585274,1599447,62.619178,548544,POINT (1083562.578 1811618.167),0.908995
1,41.64,-87.95,165.943265,1453663,182.646918,1599987,62.639384,548721,POINT (1089029.391 1811641.853),0.908547
2,41.64,-87.93,165.955936,1453774,182.663584,1600133,62.632192,548658,POINT (1094496.205 1811666.806),0.908533
3,41.64,-87.91,166.399315,1457658,185.094749,1621430,61.825799,541594,POINT (1099963.021 1811693.028),0.898995
4,41.64,-87.89,166.332648,1457074,185.556164,1625472,61.631849,539895,POINT (1105429.838 1811720.517),0.896401
...,...,...,...,...,...,...,...,...,...,...
772,42.04,-87.33,158.380251,1387411,160.960616,1410015,64.334817,563573,POINT (1256798.315 1958764.788),0.983969
773,42.04,-87.31,158.618721,1389500,160.726256,1407962,64.344977,563662,POINT (1262231.265 1958829.138),0.986887
774,42.04,-87.29,158.655137,1389819,160.997489,1410338,64.251484,562843,POINT (1267664.219 1958894.757),0.985451
775,42.04,-87.27,158.976712,1392636,161.735845,1416806,64.047603,561057,POINT (1273097.176 1958961.648),0.982941
776,42.04,-87.25,158.464612,1388150,161.244635,1412503,63.771005,558634,POINT (1278530.137 1959029.808),0.982759

### Load building footprints

In [5]:
buildings_gdf = gpd.read_file('data/footprints/Buildings.shp')

In [6]:
print('buildings gdf crs: ', buildings_gdf.crs)
print('buildings gdf shape: ', buildings_gdf.shape)

buildings gdf crs:  EPSG:3435
buildings gdf shape:  (820154, 43)

## Match radiation points to building footprints

In [7]:
joined_gdf = buildings_gdf.sjoin_nearest(sum_gdf, how='left', distance_col='distance_meters')

In [8]:
# check if the join worked properly and see how far off are the interpolations
(joined_gdf.sort_values(by='distance_meters', ascending=True)).tail(25)

,BLDG_ID,CDB_CITY_I,BLDG_STATU,F_ADD1,T_ADD1,PRE_DIR1,ST_NAME1,ST_TYPE1,UNIT_NAME,NON_STANDA,...,lat,lon,GHI_mean,GHI_sum,DNI_mean,DNI_sum,DHI_mean,DHI_sum,GHI/DNI,distance_meters
58392,617574,None,ACTIVE,7923,7923,S,LOWE,AVE,None,None,...,41.74,-87.65,164.101941,1437533,176.275228,1544171,63.545548,556659,0.930942,4510.665344
333703,564558,None,ACTIVE,6802,6802,S,BELL,AVE,None,None,...,41.76,-87.67,165.561301,1450317,180.846119,1584212,63.236986,553956,0.915482,4511.050973
695387,166425,None,ACTIVE,0,0,None,None,None,None,None,...,41.94,-87.67,162.751712,1425705,172.719977,1513027,64.082192,561360,0.942287,4511.220292
525360,308931,None,ACTIVE,1633,1633,N,SAYRE,AVE,None,None,...,41.92,-87.79,164.720320,1442950,179.076941,1568714,63.232991,553921,0.919830,4511.271270
251595,248950,None,ACTIVE,0,0,None,None,None,None,None,...,41.92,-87.73,164.314954,1439399,179.137671,1569246,62.620205,548553,0.917255,4512.118397
666282,168143,None,ACTIVE,0,0,None,None,None,None,None,...,41.96,-87.77,164.217694,1438547,179.457534,1572048,62.583790,548234,0.915078,4512.291953
448692,771680,None,ACTIVE,11200,11218,S,TORRENCE,AVE,OOM,None,...,41.70,-87.57,163.784018,1434748,175.179795,1534575,63.544635,556651,0.934948,4512.398303
469549,564225,None,ACTIVE,6811,6811,S,BISHOP,ST,None,None,...,41.78,-87.67,165.313470,1448146,180.029680,1577060,63.085388,552628,0.918257,4513.476365
496491,500270,None,ACTIVE,5605,5605,S,NEVA,AVE,None,None,...,41.80,-87.79,165.449658,1449339,179.960959,1576458,63.711872,558116,0.919364,4513.921598
138285,682240,None,ACTIVE,0,0,None,None,None,None,None,...,41.74,-87.57,161.560731,1415272,171.170548,1499454,63.297831,554489,0.943858,4514.030727
267844,565183,None,ACTIVE,0,0,None,None,None,None,None,...,41.76,-87.71,165.575913,1450445,180.083333,1577530,63.748744,558439,0.919441,4514.657399
230663,168126,None,ACTIVE,0,0,None,None,None,None,None,...,41.96,-87.75,164.294635,1439221,178.740068,1565763,63.075114,552538,0.919182,4514.901007
306333,165809,None,ACTIVE,0,0,None,None,None,None,None,...,41.96,-87.65,160.361530,1404767,170.351142,1492276,62.996347,551848,0.941359,4514.984474
741761,306659,None,ACTIVE,1522,1522,N,HUDSON,AVE,None,None,...,41.90,-87.63,159.177283,1394393,170.658105,1494965,61.876484,542038,0.932726,4515.152623
50638,99811,None,ACTIVE,0,0,None,None,None,None,None,...,41.98,-87.73,163.855594,1435375,175.969635,1541494,63.111872,552860,0.931158,4516.117782
572669,98929,None,ACTIVE,0,0,None,None,None,None,None,...,41.98,-87.67,163.461872,1431926,174.645091,1529891,63.141895,553123,0.935966,4516.368798
190133,167705,None,ACTIVE,0,0,None,None,None,None,None,...,41.96,-87.75,164.294635,1439221,178.740068,1565763,63.075114,552538,0.919182,4516.405867
754593,724629,None,ACTIVE,0,0,None,None,None,None,None,...,41.72,-87.63,164.358219,1439778,176.962100,1550188,63.440183,555736,0.928776,4516.951848
444495,249673,None,ACTIVE,0,0,None,None,None,None,None,...,41.92,-87.79,164.720320,1442950,179.076941,1568714,63.232991,553921,0.919830,4519.157299
403432,773509,None,ACTIVE,0,0,None,None,None,None,None,...,41.68,-87.71,164.288927,1439171,178.033562,1559574,63.257991,554140,0.922798,4521.467486
802163,308471,None,ACTIVE,0,0,None,None,None,None,None,...,41.90,-87.77,164.329452,1439526,179.811644,1575150,62.775457,549913,0.913898,4522.986746
581975,443882,None,ACTIVE,0,0,None,None,None,None,None,...,41.80,-87.75,165.706849,1451592,179.782078,1574891,63.951027,560211,0.921710,4523.010925
116838,101003,None,ACTIVE,0,0,None,None,None,None,None,...,41.98,-87.79,164.671689,1442524,180.199886,1578551,62.552283,547958,0.913828,4523.406927
143977,168127,None,ACTIVE,0,0,None,None,None,None,None,...,41.96,-87.77,164.217694,1438547,179.457534,1572048,62.583790,548234,0.915078,4529.639442
781954,442707,None,ACTIVE,0,0,None,None,None,None,None,...,41.80,-87.65,162.924201,1427216,173.194749,1517186,64.123858,561725,0.940699,4530.174777

Compute surface area in $m^2$ from geometry

In [9]:
# Convert to projected CRS (e.g., for Chicago, use EPSG:26971)
joined_gdf = joined_gdf.to_crs(epsg=26916)

# Compute surface area in m²
joined_gdf["surface_area"] = joined_gdf.geometry.area

# Convert back to lat/lon
joined_gdf = joined_gdf.to_crs(epsg=3435)

## Solar potential

To first order, 

$\text{kWh = GHI × area × efficiency / 100}$

so we can already compute the annual solar energy output at each building given that

- We have the column GHI_sum (Wh/m²/year)
- We have the column SHAPE_AREA which is the roof surface area in m²
- We can assume that the system efficiency is ~15%

In [10]:
# trim data to avoid slowness during visualizations
gdf = joined_gdf.copy()
gdf = gdf[['GHI_sum', 'GHI/DNI', 'lon', 'lat', 'BLDG_ID', 'surface_area', 'geometry']]
gdf.columns = [col.lower() for col in gdf.columns]

In [11]:
# compute orientation of the longest edge as a proxy for roof orientation (azimuth)
gdf["orientation_angle"] = gdf.geometry.apply(get_orientation)

# classify orientation (cardinal direction)
gdf["orientation"] = gdf["orientation_angle"].apply(azimuth_to_orientation)

In [12]:
print(gdf.columns.tolist())

['ghi_sum', 'ghi/dni', 'lon', 'lat', 'bldg_id', 'surface_area', 'geometry', 'orientation_angle', 'orientation']

In [13]:
# estimate kwh per year
gdf["raw_kwh_estimate"] = gdf.apply(
    lambda row: get_raw_kwh(row["ghi_sum"], row["surface_area"]),
    axis=1
)

In [14]:
gdf = get_adj_kwh(gdf, "raw_kwh_estimate")
gdf.head()

,ghi_sum,ghi/dni,lon,lat,bldg_id,surface_area,geometry,orientation_angle,orientation,raw_kwh_estimate,orientation_cat,orientation_factor,kwh_estimate
0,1415272,0.943858,-87.57,41.74,634694,101.114277,"POLYGON ((1195174.643 1850643.039, 1195174.143...",0.578726,North,14875.682074,North,0.80,11900.545659
1,1448374,0.918329,-87.71,41.78,520117,69.882056,"POLYGON ((1153540.143 1864316.539, 1153539.143...",91.231977,East,10521.335955,East,0.92,9679.629078
2,1415468,0.933682,-87.57,41.76,580168,636.616897,"POLYGON ((1190036.643 1857036.539, 1190036.143...",181.468801,South,93670.472452,South,1.00,93670.472452
3,1425211,0.937486,-87.69,41.96,156735,108.105886,"POLYGON ((1160053.643 1925961.539, 1160049.643...",2.121096,North,16015.960845,North,0.80,12812.768676
4,1431263,0.937171,-87.69,41.92,261847,120.349070,"POLYGON ((1157022.143 1916159.539, 1157018.643...",181.847610,South,17905.509264,South,1.00,17905.509264

## 🌍 Climate Impact

We can also estimate avoided CO₂ emissions by replacing grid electricity with clean solar.

CO₂ Avoided per Year (kg):

$\text{CO}_2 \text{Avoided = Annual Energy Output (kWh)} \times \text{Grid Emission Factor (kgCO}_2\text{/kWh)}$

A typical U.S. emission factor is ~0.4–0.5 kgCO₂/kWh, but this varies by region. Source specific kgCO₂/kWh are typically 0.90 for coal, 0.40 gas, ~0.05 for nuclear.

In [15]:
# estimate avoided CO2 per year
gdf["co2_avoided_t"] = gdf.apply(
    lambda row: get_co2_avoided(row["kwh_estimate"]),
    axis=1
)

## 💰 Financial Metrics

To understand the economic feasibility of rooftop solar, we compute basic financial indicators using standard assumptions for installation costs and electricity prices.

* System Size (kW):
We estimate installed capacity from roof area using a typical power density of ~0.2 kW/m².
* CAPEX (Capital Expenditure):
Initial cost of installing solar panels, estimated as:

$\text{CAPEX=System Size (kW)×Cost per kW}$

A common assumption is \$1000–\$1500/kW installed.

* Annual Savings:
Money saved by offsetting electricity consumption, calculated as:


$\text{Savings=Annual Energy Output (kWh)}\times\text{Electricity Price (\$/kWh)}$

* Simple Payback Period (years):
How long until the installation pays for itself:


$\text{Payback}=\frac{\text{CAPEX}}{\text{Annual Savings}}$

* ROI (Return on Investment):
Basic measure of profitability:

$\text{ROI}=\frac{\text{Annual Savings}}{\text{CAPEX}}$

In [16]:
gdf_finance = get_finance_computations(gdf)
gdf_finance.head()

,ghi_sum,ghi/dni,lon,lat,bldg_id,surface_area,geometry,orientation_angle,orientation,raw_kwh_estimate,...,kwh_estimate,co2_avoided_t,annual_kwh,system_kw,capex_per_kw_adj,capex_usd,annual_savings_usd,annual_om_usd,simple_payback_years,simple_roi
0,1415272,0.943858,-87.57,41.74,634694,101.114277,"POLYGON ((1195174.643 1850643.039, 1195174.143...",0.578726,North,14875.682074,...,11900.545659,4.760218,11900.545659,13.650427,1434.971302,19587.971513,1785.081849,195.879715,12.325664,0.081132
1,1448374,0.918329,-87.71,41.78,520117,69.882056,"POLYGON ((1153540.143 1864316.539, 1153539.143...",91.231977,East,10521.335955,...,9679.629078,3.871852,9679.629078,9.434078,1386.269992,13078.178636,1451.944362,130.781786,9.898993,0.101020
2,1415468,0.933682,-87.57,41.76,580168,636.616897,"POLYGON ((1190036.643 1857036.539, 1190036.143...",181.468801,South,93670.472452,...,93670.472452,37.468189,93670.472452,85.943281,1200.416861,103167.763699,14050.570868,1031.677637,7.924465,0.126191
3,1425211,0.937486,-87.69,41.96,156735,108.105886,"POLYGON ((1160053.643 1925961.539, 1160049.643...",2.121096,North,16015.960845,...,12812.768676,5.125107,12812.768676,14.594295,1470.494265,21460.826463,1921.915301,214.608265,12.569987,0.079555
4,1431263,0.937171,-87.69,41.92,261847,120.349070,"POLYGON ((1157022.143 1916159.539, 1157018.643...",181.847610,South,17905.509264,...,17905.509264,7.162204,17905.509264,16.247124,1254.348057,20379.549034,2685.826390,203.795490,8.210836,0.121790

In [17]:
# save geodataframe
gdf_finance.to_file('data/solar_summary.geojson', driver='GeoJSON')
gdf_finance.drop(columns="geometry").to_csv("data/solar_summary.csv", index=False)

Sort buildings from highest to lowest potential energy output and save the top 100.

In [18]:
col_pop = "kwh_estimate"
if col_pop not in gdf_finance.columns:
    gdf_finance.insert(0, col_pop, gdf.pop(col_pop))

# Sort by energy output
gdf_sorted = gdf_finance.sort_values(by="kwh_estimate", ascending=False)

# Take top 100 and bottom 100
top_100 = gdf_sorted.head(100).copy()
top_100["ranking"] = "Top 100"

bottom_100 = gdf_sorted.tail(100).copy()
bottom_100["ranking"] = "Bottom 100"

# Combine into a single GeoDataFrame
top_bottom_100 = pd.concat([top_100, bottom_100])

# save to geojson

top_bottom_100.to_file("data/top_bottom_100_buildings.geojson", driver="GeoJSON")
top_bottom_100.drop(columns="geometry").to_csv("data/top_bottom_100_buildings.csv", index=False)
top_bottom_100.tail()

,ghi_sum,ghi/dni,lon,lat,bldg_id,surface_area,geometry,orientation_angle,orientation,raw_kwh_estimate,...,co2_avoided_t,annual_kwh,system_kw,capex_per_kw_adj,capex_usd,annual_savings_usd,annual_om_usd,simple_payback_years,simple_roi,ranking
563700,1450445,0.919441,-87.71,41.76,840667,0.390372,"POLYGON ((1156456.043 1856056.039, 1156456.043...",5.869691e-08,North,58.857881,...,0.018835,47.086305,0.052700,1779.772762,93.794460,7.062946,0.937945,15.313378,0.065302,Bottom 100
582165,1437272,0.921736,-87.71,41.70,840551,0.264581,"POLYGON ((1155899.243 1832153.239, 1155899.243...",3.600000e+02,North,39.529537,...,0.012649,31.623629,0.035718,1879.750525,67.141687,4.743544,0.671417,16.488110,0.060650,Bottom 100
75015,1430934,0.937150,-87.67,41.86,840559,0.187060,"POLYGON ((1165773.143 1893291.939, 1165773.243...",8.663354e+01,East,27.824353,...,0.010239,25.598405,0.025253,1812.021326,45.759161,3.839761,0.457592,13.529531,0.073912,Bottom 100
818569,1402521,0.953712,-87.63,41.86,0,0.175582,"POLYGON ((1175766.159 1894786.91, 1175760.143 ...",5.551739e+00,North,25.598435,...,0.008191,20.478748,0.023704,1765.314498,41.844214,3.071812,0.418442,15.770214,0.063411,Bottom 100
393026,1431926,0.935966,-87.67,41.98,871905,0.070580,"POLYGON ((1166147.209 1933153.446, 1166144.645...",1.340421e+01,North,10.505703,...,0.003362,8.404562,0.009528,1769.514589,16.860403,1.260684,0.168604,15.438794,0.064772,Bottom 100

### Visualize location of top 100 candidate buildings

In [19]:
import plotly.express as px
import json
from app.viz import plot_top_k_mapbox

fig_top_k = plot_top_k_mapbox(top_k)
fig_top_k.show()

NameError: name 'top_k' is not defined